version: '3.9'

services:

  db:
    image: postgres
    container_name: db_postgres_openloot_db
    restart: always
    environment:
      POSTGRES_PASSWORD: Qwerty123
      POSTGRES_USER: admin
      POSTGRES_DB: openloot_db


  bot:
    build: .
    restart: always
    command: bash -c "python Synchronous_telega.py"
    ports:
      - 80:80
    depends_on:
      - db

  notif:
    build: .
    restart: always
    command: bash -c "python notifications.py"
    depends_on:
      - db

